// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tiagods/webtool/apps/api/domain/ports/outbound (interfaces: ProtocoloCounter)
//
// Generated by this command:
//
//	mockgen -typed -package mocks -destination protocolo_counter.go github.com/tiagods/webtool/apps/api/domain/ports/outbound ProtocoloCounter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProtocoloCounter is a mock of ProtocoloCounter interface.
type MockProtocoloCounter struct {
	ctrl     *gomock.Controller
	recorder *MockProtocoloCounterMockRecorder
	isgomock struct{}
}

// MockProtocoloCounterMockRecorder is the mock recorder for MockProtocoloCounter.
type MockProtocoloCounterMockRecorder struct {
	mock *MockProtocoloCounter
}

// NewMockProtocoloCounter creates a new mock instance.
func NewMockProtocoloCounter(ctrl *gomock.Controller) *MockProtocoloCounter {
	mock := &MockProtocoloCounter{ctrl: ctrl}
	mock.recorder = &MockProtocoloCounterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProtocoloCounter) EXPECT() *MockProtocoloCounterMockRecorder {
	return m.recorder
}

// Proximo mocks base method.
func (m *MockProtocoloCounter) Proximo(ctx context.Context, prefix string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Proximo", ctx, prefix)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Proximo indicates an expected call of Proximo.
func (mr *MockProtocoloCounterMockRecorder) Proximo(ctx, prefix any) *MockProtocoloCounterProximoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Proximo", reflect.TypeOf((*MockProtocoloCounter)(nil).Proximo), ctx, prefix)
	return &MockProtocoloCounterProximoCall{Call: call}
}

// MockProtocoloCounterProximoCall wrap *gomock.Call
type MockProtocoloCounterProximoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProtocoloCounterProximoCall) Return(arg0 string, arg1 error) *MockProtocoloCounterProximoCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProtocoloCounterProximoCall) Do(f func(context.Context, string) (string, error)) *MockProtocoloCounterProximoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProtocoloCounterProximoCall) DoAndReturn(f func(context.Context, string) (string, error)) *MockProtocoloCounterProximoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
