// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tiagods/webtool/apps/api/domain/ports/outbound (interfaces: SubmissaoPublisher)
//
// Generated by this command:
//
//	mockgen -typed -package mocks -destination submissao_publisher.go github.com/tiagods/webtool/apps/api/domain/ports/outbound SubmissaoPublisher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/tiagods/webtool/apps/api/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockSubmissaoPublisher is a mock of SubmissaoPublisher interface.
type MockSubmissaoPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockSubmissaoPublisherMockRecorder
	isgomock struct{}
}

// MockSubmissaoPublisherMockRecorder is the mock recorder for MockSubmissaoPublisher.
type MockSubmissaoPublisherMockRecorder struct {
	mock *MockSubmissaoPublisher
}

// NewMockSubmissaoPublisher creates a new mock instance.
func NewMockSubmissaoPublisher(ctrl *gomock.Controller) *MockSubmissaoPublisher {
	mock := &MockSubmissaoPublisher{ctrl: ctrl}
	mock.recorder = &MockSubmissaoPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubmissaoPublisher) EXPECT() *MockSubmissaoPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockSubmissaoPublisher) Publish(ctx context.Context, msg entity.SubmissaoMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockSubmissaoPublisherMockRecorder) Publish(ctx, msg any) *MockSubmissaoPublisherPublishCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockSubmissaoPublisher)(nil).Publish), ctx, msg)
	return &MockSubmissaoPublisherPublishCall{Call: call}
}

// MockSubmissaoPublisherPublishCall wrap *gomock.Call
type MockSubmissaoPublisherPublishCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSubmissaoPublisherPublishCall) Return(arg0 error) *MockSubmissaoPublisherPublishCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSubmissaoPublisherPublishCall) Do(f func(context.Context, entity.SubmissaoMessage) error) *MockSubmissaoPublisherPublishCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSubmissaoPublisherPublishCall) DoAndReturn(f func(context.Context, entity.SubmissaoMessage) error) *MockSubmissaoPublisherPublishCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
