// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tiagods/webtool/apps/api/domain/ports/outbound (interfaces: TokenService)
//
// Generated by this command:
//
//	mockgen -typed -package mocks -destination token_service.go github.com/tiagods/webtool/apps/api/domain/ports/outbound TokenService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTokenService is a mock of TokenService interface.
type MockTokenService struct {
	ctrl     *gomock.Controller
	recorder *MockTokenServiceMockRecorder
	isgomock struct{}
}

// MockTokenServiceMockRecorder is the mock recorder for MockTokenService.
type MockTokenServiceMockRecorder struct {
	mock *MockTokenService
}

// NewMockTokenService creates a new mock instance.
func NewMockTokenService(ctrl *gomock.Controller) *MockTokenService {
	mock := &MockTokenService{ctrl: ctrl}
	mock.recorder = &MockTokenServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenService) EXPECT() *MockTokenServiceMockRecorder {
	return m.recorder
}

// AssinarAceite mocks base method.
func (m *MockTokenService) AssinarAceite(sessionID, versaoTermo string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssinarAceite", sessionID, versaoTermo)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssinarAceite indicates an expected call of AssinarAceite.
func (mr *MockTokenServiceMockRecorder) AssinarAceite(sessionID, versaoTermo any) *MockTokenServiceAssinarAceiteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssinarAceite", reflect.TypeOf((*MockTokenService)(nil).AssinarAceite), sessionID, versaoTermo)
	return &MockTokenServiceAssinarAceiteCall{Call: call}
}

// MockTokenServiceAssinarAceiteCall wrap *gomock.Call
type MockTokenServiceAssinarAceiteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTokenServiceAssinarAceiteCall) Return(arg0 string, arg1 error) *MockTokenServiceAssinarAceiteCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTokenServiceAssinarAceiteCall) Do(f func(string, string) (string, error)) *MockTokenServiceAssinarAceiteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTokenServiceAssinarAceiteCall) DoAndReturn(f func(string, string) (string, error)) *MockTokenServiceAssinarAceiteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AssinarSessao mocks base method.
func (m *MockTokenService) AssinarSessao(sessionID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssinarSessao", sessionID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssinarSessao indicates an expected call of AssinarSessao.
func (mr *MockTokenServiceMockRecorder) AssinarSessao(sessionID any) *MockTokenServiceAssinarSessaoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssinarSessao", reflect.TypeOf((*MockTokenService)(nil).AssinarSessao), sessionID)
	return &MockTokenServiceAssinarSessaoCall{Call: call}
}

// MockTokenServiceAssinarSessaoCall wrap *gomock.Call
type MockTokenServiceAssinarSessaoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTokenServiceAssinarSessaoCall) Return(arg0 string, arg1 error) *MockTokenServiceAssinarSessaoCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTokenServiceAssinarSessaoCall) Do(f func(string) (string, error)) *MockTokenServiceAssinarSessaoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTokenServiceAssinarSessaoCall) DoAndReturn(f func(string) (string, error)) *MockTokenServiceAssinarSessaoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// VerificarAceite mocks base method.
func (m *MockTokenService) VerificarAceite(token string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerificarAceite", token)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerificarAceite indicates an expected call of VerificarAceite.
func (mr *MockTokenServiceMockRecorder) VerificarAceite(token any) *MockTokenServiceVerificarAceiteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerificarAceite", reflect.TypeOf((*MockTokenService)(nil).VerificarAceite), token)
	return &MockTokenServiceVerificarAceiteCall{Call: call}
}

// MockTokenServiceVerificarAceiteCall wrap *gomock.Call
type MockTokenServiceVerificarAceiteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTokenServiceVerificarAceiteCall) Return(versaoTermo string, err error) *MockTokenServiceVerificarAceiteCall {
	c.Call = c.Call.Return(versaoTermo, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTokenServiceVerificarAceiteCall) Do(f func(string) (string, error)) *MockTokenServiceVerificarAceiteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTokenServiceVerificarAceiteCall) DoAndReturn(f func(string) (string, error)) *MockTokenServiceVerificarAceiteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// VerificarSessao mocks base method.
func (m *MockTokenService) VerificarSessao(token string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerificarSessao", token)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerificarSessao indicates an expected call of VerificarSessao.
func (mr *MockTokenServiceMockRecorder) VerificarSessao(token any) *MockTokenServiceVerificarSessaoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerificarSessao", reflect.TypeOf((*MockTokenService)(nil).VerificarSessao), token)
	return &MockTokenServiceVerificarSessaoCall{Call: call}
}

// MockTokenServiceVerificarSessaoCall wrap *gomock.Call
type MockTokenServiceVerificarSessaoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTokenServiceVerificarSessaoCall) Return(sessionID string, err error) *MockTokenServiceVerificarSessaoCall {
	c.Call = c.Call.Return(sessionID, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTokenServiceVerificarSessaoCall) Do(f func(string) (string, error)) *MockTokenServiceVerificarSessaoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTokenServiceVerificarSessaoCall) DoAndReturn(f func(string) (string, error)) *MockTokenServiceVerificarSessaoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
