// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tiagods/webtool/apps/backend/domain/ports/inbound (interfaces: AceiteUseCase)
//
// Generated by this command:
//
//	mockgen -typed -package mocks -destination aceite_use_case.go github.com/tiagods/webtool/apps/backend/domain/ports/inbound AceiteUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAceiteUseCase is a mock of AceiteUseCase interface.
type MockAceiteUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockAceiteUseCaseMockRecorder
	isgomock struct{}
}

// MockAceiteUseCaseMockRecorder is the mock recorder for MockAceiteUseCase.
type MockAceiteUseCaseMockRecorder struct {
	mock *MockAceiteUseCase
}

// NewMockAceiteUseCase creates a new mock instance.
func NewMockAceiteUseCase(ctrl *gomock.Controller) *MockAceiteUseCase {
	mock := &MockAceiteUseCase{ctrl: ctrl}
	mock.recorder = &MockAceiteUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAceiteUseCase) EXPECT() *MockAceiteUseCaseMockRecorder {
	return m.recorder
}

// RegistrarAceite mocks base method.
func (m *MockAceiteUseCase) RegistrarAceite(ctx context.Context, versaoTermo, ip, userAgent string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegistrarAceite", ctx, versaoTermo, ip, userAgent)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegistrarAceite indicates an expected call of RegistrarAceite.
func (mr *MockAceiteUseCaseMockRecorder) RegistrarAceite(ctx, versaoTermo, ip, userAgent any) *MockAceiteUseCaseRegistrarAceiteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegistrarAceite", reflect.TypeOf((*MockAceiteUseCase)(nil).RegistrarAceite), ctx, versaoTermo, ip, userAgent)
	return &MockAceiteUseCaseRegistrarAceiteCall{Call: call}
}

// MockAceiteUseCaseRegistrarAceiteCall wrap *gomock.Call
type MockAceiteUseCaseRegistrarAceiteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAceiteUseCaseRegistrarAceiteCall) Return(arg0 string, arg1 error) *MockAceiteUseCaseRegistrarAceiteCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAceiteUseCaseRegistrarAceiteCall) Do(f func(context.Context, string, string, string) (string, error)) *MockAceiteUseCaseRegistrarAceiteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAceiteUseCaseRegistrarAceiteCall) DoAndReturn(f func(context.Context, string, string, string) (string, error)) *MockAceiteUseCaseRegistrarAceiteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
