// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tiagods/webtool/apps/backend/domain/ports/inbound (interfaces: DocumentoUseCase)
//
// Generated by this command:
//
//	mockgen -typed -package mocks -destination documento_use_case.go github.com/tiagods/webtool/apps/backend/domain/ports/inbound DocumentoUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDocumentoUseCase is a mock of DocumentoUseCase interface.
type MockDocumentoUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockDocumentoUseCaseMockRecorder
	isgomock struct{}
}

// MockDocumentoUseCaseMockRecorder is the mock recorder for MockDocumentoUseCase.
type MockDocumentoUseCaseMockRecorder struct {
	mock *MockDocumentoUseCase
}

// NewMockDocumentoUseCase creates a new mock instance.
func NewMockDocumentoUseCase(ctrl *gomock.Controller) *MockDocumentoUseCase {
	mock := &MockDocumentoUseCase{ctrl: ctrl}
	mock.recorder = &MockDocumentoUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDocumentoUseCase) EXPECT() *MockDocumentoUseCaseMockRecorder {
	return m.recorder
}

// ConfirmarUpload mocks base method.
func (m *MockDocumentoUseCase) ConfirmarUpload(ctx context.Context, sessionID, campo, contentType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmarUpload", ctx, sessionID, campo, contentType)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmarUpload indicates an expected call of ConfirmarUpload.
func (mr *MockDocumentoUseCaseMockRecorder) ConfirmarUpload(ctx, sessionID, campo, contentType any) *MockDocumentoUseCaseConfirmarUploadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmarUpload", reflect.TypeOf((*MockDocumentoUseCase)(nil).ConfirmarUpload), ctx, sessionID, campo, contentType)
	return &MockDocumentoUseCaseConfirmarUploadCall{Call: call}
}

// MockDocumentoUseCaseConfirmarUploadCall wrap *gomock.Call
type MockDocumentoUseCaseConfirmarUploadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDocumentoUseCaseConfirmarUploadCall) Return(arg0 error) *MockDocumentoUseCaseConfirmarUploadCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDocumentoUseCaseConfirmarUploadCall) Do(f func(context.Context, string, string, string) error) *MockDocumentoUseCaseConfirmarUploadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDocumentoUseCaseConfirmarUploadCall) DoAndReturn(f func(context.Context, string, string, string) error) *MockDocumentoUseCaseConfirmarUploadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PresignarDocumento mocks base method.
func (m *MockDocumentoUseCase) PresignarDocumento(ctx context.Context, sessionID, campo, contentType string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresignarDocumento", ctx, sessionID, campo, contentType)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignarDocumento indicates an expected call of PresignarDocumento.
func (mr *MockDocumentoUseCaseMockRecorder) PresignarDocumento(ctx, sessionID, campo, contentType any) *MockDocumentoUseCasePresignarDocumentoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignarDocumento", reflect.TypeOf((*MockDocumentoUseCase)(nil).PresignarDocumento), ctx, sessionID, campo, contentType)
	return &MockDocumentoUseCasePresignarDocumentoCall{Call: call}
}

// MockDocumentoUseCasePresignarDocumentoCall wrap *gomock.Call
type MockDocumentoUseCasePresignarDocumentoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDocumentoUseCasePresignarDocumentoCall) Return(arg0 string, arg1 error) *MockDocumentoUseCasePresignarDocumentoCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDocumentoUseCasePresignarDocumentoCall) Do(f func(context.Context, string, string, string) (string, error)) *MockDocumentoUseCasePresignarDocumentoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDocumentoUseCasePresignarDocumentoCall) DoAndReturn(f func(context.Context, string, string, string) (string, error)) *MockDocumentoUseCasePresignarDocumentoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ValidarPedido mocks base method.
func (m *MockDocumentoUseCase) ValidarPedido(campo, contentType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidarPedido", campo, contentType)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidarPedido indicates an expected call of ValidarPedido.
func (mr *MockDocumentoUseCaseMockRecorder) ValidarPedido(campo, contentType any) *MockDocumentoUseCaseValidarPedidoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidarPedido", reflect.TypeOf((*MockDocumentoUseCase)(nil).ValidarPedido), campo, contentType)
	return &MockDocumentoUseCaseValidarPedidoCall{Call: call}
}

// MockDocumentoUseCaseValidarPedidoCall wrap *gomock.Call
type MockDocumentoUseCaseValidarPedidoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDocumentoUseCaseValidarPedidoCall) Return(arg0 error) *MockDocumentoUseCaseValidarPedidoCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDocumentoUseCaseValidarPedidoCall) Do(f func(string, string) error) *MockDocumentoUseCaseValidarPedidoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDocumentoUseCaseValidarPedidoCall) DoAndReturn(f func(string, string) error) *MockDocumentoUseCaseValidarPedidoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
