// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tiagods/webtool/apps/backend/domain/ports/inbound (interfaces: NotificacaoUseCase)
//
// Generated by this command:
//
//	mockgen -typed -package mocks -destination notificacao_use_case.go github.com/tiagods/webtool/apps/backend/domain/ports/inbound NotificacaoUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/tiagods/webtool/apps/backend/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificacaoUseCase is a mock of NotificacaoUseCase interface.
type MockNotificacaoUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockNotificacaoUseCaseMockRecorder
	isgomock struct{}
}

// MockNotificacaoUseCaseMockRecorder is the mock recorder for MockNotificacaoUseCase.
type MockNotificacaoUseCaseMockRecorder struct {
	mock *MockNotificacaoUseCase
}

// NewMockNotificacaoUseCase creates a new mock instance.
func NewMockNotificacaoUseCase(ctrl *gomock.Controller) *MockNotificacaoUseCase {
	mock := &MockNotificacaoUseCase{ctrl: ctrl}
	mock.recorder = &MockNotificacaoUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificacaoUseCase) EXPECT() *MockNotificacaoUseCaseMockRecorder {
	return m.recorder
}

// Processar mocks base method.
func (m *MockNotificacaoUseCase) Processar(ctx context.Context, msg entity.SubmissaoMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Processar", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Processar indicates an expected call of Processar.
func (mr *MockNotificacaoUseCaseMockRecorder) Processar(ctx, msg any) *MockNotificacaoUseCaseProcessarCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Processar", reflect.TypeOf((*MockNotificacaoUseCase)(nil).Processar), ctx, msg)
	return &MockNotificacaoUseCaseProcessarCall{Call: call}
}

// MockNotificacaoUseCaseProcessarCall wrap *gomock.Call
type MockNotificacaoUseCaseProcessarCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockNotificacaoUseCaseProcessarCall) Return(arg0 error) *MockNotificacaoUseCaseProcessarCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockNotificacaoUseCaseProcessarCall) Do(f func(context.Context, entity.SubmissaoMessage) error) *MockNotificacaoUseCaseProcessarCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockNotificacaoUseCaseProcessarCall) DoAndReturn(f func(context.Context, entity.SubmissaoMessage) error) *MockNotificacaoUseCaseProcessarCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
