// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tiagods/webtool/apps/backend/domain/ports/inbound (interfaces: RascunhoUseCase)
//
// Generated by this command:
//
//	mockgen -typed -package mocks -destination rascunho_use_case.go github.com/tiagods/webtool/apps/backend/domain/ports/inbound RascunhoUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	json "encoding/json"
	reflect "reflect"

	entity "github.com/tiagods/webtool/apps/backend/domain/entity"
	validation "github.com/tiagods/webtool/apps/backend/domain/validation"
	gomock "go.uber.org/mock/gomock"
)

// MockRascunhoUseCase is a mock of RascunhoUseCase interface.
type MockRascunhoUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockRascunhoUseCaseMockRecorder
	isgomock struct{}
}

// MockRascunhoUseCaseMockRecorder is the mock recorder for MockRascunhoUseCase.
type MockRascunhoUseCaseMockRecorder struct {
	mock *MockRascunhoUseCase
}

// NewMockRascunhoUseCase creates a new mock instance.
func NewMockRascunhoUseCase(ctrl *gomock.Controller) *MockRascunhoUseCase {
	mock := &MockRascunhoUseCase{ctrl: ctrl}
	mock.recorder = &MockRascunhoUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRascunhoUseCase) EXPECT() *MockRascunhoUseCaseMockRecorder {
	return m.recorder
}

// Buscar mocks base method.
func (m *MockRascunhoUseCase) Buscar(ctx context.Context, sessionID string) (*entity.Rascunho, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Buscar", ctx, sessionID)
	ret0, _ := ret[0].(*entity.Rascunho)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Buscar indicates an expected call of Buscar.
func (mr *MockRascunhoUseCaseMockRecorder) Buscar(ctx, sessionID any) *MockRascunhoUseCaseBuscarCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Buscar", reflect.TypeOf((*MockRascunhoUseCase)(nil).Buscar), ctx, sessionID)
	return &MockRascunhoUseCaseBuscarCall{Call: call}
}

// MockRascunhoUseCaseBuscarCall wrap *gomock.Call
type MockRascunhoUseCaseBuscarCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRascunhoUseCaseBuscarCall) Return(arg0 *entity.Rascunho, arg1 error) *MockRascunhoUseCaseBuscarCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRascunhoUseCaseBuscarCall) Do(f func(context.Context, string) (*entity.Rascunho, error)) *MockRascunhoUseCaseBuscarCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRascunhoUseCaseBuscarCall) DoAndReturn(f func(context.Context, string) (*entity.Rascunho, error)) *MockRascunhoUseCaseBuscarCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Salvar mocks base method.
func (m *MockRascunhoUseCase) Salvar(ctx context.Context, sessionID string, raw json.RawMessage) ([]validation.Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Salvar", ctx, sessionID, raw)
	ret0, _ := ret[0].([]validation.Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Salvar indicates an expected call of Salvar.
func (mr *MockRascunhoUseCaseMockRecorder) Salvar(ctx, sessionID, raw any) *MockRascunhoUseCaseSalvarCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Salvar", reflect.TypeOf((*MockRascunhoUseCase)(nil).Salvar), ctx, sessionID, raw)
	return &MockRascunhoUseCaseSalvarCall{Call: call}
}

// MockRascunhoUseCaseSalvarCall wrap *gomock.Call
type MockRascunhoUseCaseSalvarCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRascunhoUseCaseSalvarCall) Return(arg0 []validation.Issue, arg1 error) *MockRascunhoUseCaseSalvarCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRascunhoUseCaseSalvarCall) Do(f func(context.Context, string, json.RawMessage) ([]validation.Issue, error)) *MockRascunhoUseCaseSalvarCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRascunhoUseCaseSalvarCall) DoAndReturn(f func(context.Context, string, json.RawMessage) ([]validation.Issue, error)) *MockRascunhoUseCaseSalvarCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
