// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tiagods/webtool/apps/backend/domain/ports/inbound (interfaces: SessaoUseCase)
//
// Generated by this command:
//
//	mockgen -typed -package mocks -destination sessao_use_case.go github.com/tiagods/webtool/apps/backend/domain/ports/inbound SessaoUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/tiagods/webtool/apps/backend/domain/entity"
	inbound "github.com/tiagods/webtool/apps/backend/domain/ports/inbound"
	gomock "go.uber.org/mock/gomock"
)

// MockSessaoUseCase is a mock of SessaoUseCase interface.
type MockSessaoUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockSessaoUseCaseMockRecorder
	isgomock struct{}
}

// MockSessaoUseCaseMockRecorder is the mock recorder for MockSessaoUseCase.
type MockSessaoUseCaseMockRecorder struct {
	mock *MockSessaoUseCase
}

// NewMockSessaoUseCase creates a new mock instance.
func NewMockSessaoUseCase(ctrl *gomock.Controller) *MockSessaoUseCase {
	mock := &MockSessaoUseCase{ctrl: ctrl}
	mock.recorder = &MockSessaoUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessaoUseCase) EXPECT() *MockSessaoUseCaseMockRecorder {
	return m.recorder
}

// CriarOuObter mocks base method.
func (m *MockSessaoUseCase) CriarOuObter(ctx context.Context, formType entity.FormType, sessaoToken string) (inbound.SessaoResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CriarOuObter", ctx, formType, sessaoToken)
	ret0, _ := ret[0].(inbound.SessaoResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CriarOuObter indicates an expected call of CriarOuObter.
func (mr *MockSessaoUseCaseMockRecorder) CriarOuObter(ctx, formType, sessaoToken any) *MockSessaoUseCaseCriarOuObterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CriarOuObter", reflect.TypeOf((*MockSessaoUseCase)(nil).CriarOuObter), ctx, formType, sessaoToken)
	return &MockSessaoUseCaseCriarOuObterCall{Call: call}
}

// MockSessaoUseCaseCriarOuObterCall wrap *gomock.Call
type MockSessaoUseCaseCriarOuObterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessaoUseCaseCriarOuObterCall) Return(arg0 inbound.SessaoResult, arg1 error) *MockSessaoUseCaseCriarOuObterCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessaoUseCaseCriarOuObterCall) Do(f func(context.Context, entity.FormType, string) (inbound.SessaoResult, error)) *MockSessaoUseCaseCriarOuObterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessaoUseCaseCriarOuObterCall) DoAndReturn(f func(context.Context, entity.FormType, string) (inbound.SessaoResult, error)) *MockSessaoUseCaseCriarOuObterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Encerrar mocks base method.
func (m *MockSessaoUseCase) Encerrar(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encerrar", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Encerrar indicates an expected call of Encerrar.
func (mr *MockSessaoUseCaseMockRecorder) Encerrar(ctx, sessionID any) *MockSessaoUseCaseEncerrarCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encerrar", reflect.TypeOf((*MockSessaoUseCase)(nil).Encerrar), ctx, sessionID)
	return &MockSessaoUseCaseEncerrarCall{Call: call}
}

// MockSessaoUseCaseEncerrarCall wrap *gomock.Call
type MockSessaoUseCaseEncerrarCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessaoUseCaseEncerrarCall) Return(arg0 error) *MockSessaoUseCaseEncerrarCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessaoUseCaseEncerrarCall) Do(f func(context.Context, string) error) *MockSessaoUseCaseEncerrarCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessaoUseCaseEncerrarCall) DoAndReturn(f func(context.Context, string) error) *MockSessaoUseCaseEncerrarCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// EncerrarPorToken mocks base method.
func (m *MockSessaoUseCase) EncerrarPorToken(ctx context.Context, sessaoToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncerrarPorToken", ctx, sessaoToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// EncerrarPorToken indicates an expected call of EncerrarPorToken.
func (mr *MockSessaoUseCaseMockRecorder) EncerrarPorToken(ctx, sessaoToken any) *MockSessaoUseCaseEncerrarPorTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncerrarPorToken", reflect.TypeOf((*MockSessaoUseCase)(nil).EncerrarPorToken), ctx, sessaoToken)
	return &MockSessaoUseCaseEncerrarPorTokenCall{Call: call}
}

// MockSessaoUseCaseEncerrarPorTokenCall wrap *gomock.Call
type MockSessaoUseCaseEncerrarPorTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessaoUseCaseEncerrarPorTokenCall) Return(arg0 error) *MockSessaoUseCaseEncerrarPorTokenCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessaoUseCaseEncerrarPorTokenCall) Do(f func(context.Context, string) error) *MockSessaoUseCaseEncerrarPorTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessaoUseCaseEncerrarPorTokenCall) DoAndReturn(f func(context.Context, string) error) *MockSessaoUseCaseEncerrarPorTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RequireSessao mocks base method.
func (m *MockSessaoUseCase) RequireSessao(ctx context.Context, formType entity.FormType, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequireSessao", ctx, formType, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequireSessao indicates an expected call of RequireSessao.
func (mr *MockSessaoUseCaseMockRecorder) RequireSessao(ctx, formType, sessionID any) *MockSessaoUseCaseRequireSessaoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequireSessao", reflect.TypeOf((*MockSessaoUseCase)(nil).RequireSessao), ctx, formType, sessionID)
	return &MockSessaoUseCaseRequireSessaoCall{Call: call}
}

// MockSessaoUseCaseRequireSessaoCall wrap *gomock.Call
type MockSessaoUseCaseRequireSessaoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessaoUseCaseRequireSessaoCall) Return(arg0 error) *MockSessaoUseCaseRequireSessaoCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessaoUseCaseRequireSessaoCall) Do(f func(context.Context, entity.FormType, string) error) *MockSessaoUseCaseRequireSessaoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessaoUseCaseRequireSessaoCall) DoAndReturn(f func(context.Context, entity.FormType, string) error) *MockSessaoUseCaseRequireSessaoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// VerificarAceite mocks base method.
func (m *MockSessaoUseCase) VerificarAceite(aceiteToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerificarAceite", aceiteToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerificarAceite indicates an expected call of VerificarAceite.
func (mr *MockSessaoUseCaseMockRecorder) VerificarAceite(aceiteToken any) *MockSessaoUseCaseVerificarAceiteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerificarAceite", reflect.TypeOf((*MockSessaoUseCase)(nil).VerificarAceite), aceiteToken)
	return &MockSessaoUseCaseVerificarAceiteCall{Call: call}
}

// MockSessaoUseCaseVerificarAceiteCall wrap *gomock.Call
type MockSessaoUseCaseVerificarAceiteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessaoUseCaseVerificarAceiteCall) Return(arg0 error) *MockSessaoUseCaseVerificarAceiteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessaoUseCaseVerificarAceiteCall) Do(f func(string) error) *MockSessaoUseCaseVerificarAceiteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessaoUseCaseVerificarAceiteCall) DoAndReturn(f func(string) error) *MockSessaoUseCaseVerificarAceiteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
