// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tiagods/webtool/apps/backend/domain/ports/inbound (interfaces: SubmissaoUseCase)
//
// Generated by this command:
//
//	mockgen -typed -package mocks -destination submissao_use_case.go github.com/tiagods/webtool/apps/backend/domain/ports/inbound SubmissaoUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	json "encoding/json"
	reflect "reflect"

	validation "github.com/tiagods/webtool/apps/backend/domain/validation"
	gomock "go.uber.org/mock/gomock"
)

// MockSubmissaoUseCase is a mock of SubmissaoUseCase interface.
type MockSubmissaoUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockSubmissaoUseCaseMockRecorder
	isgomock struct{}
}

// MockSubmissaoUseCaseMockRecorder is the mock recorder for MockSubmissaoUseCase.
type MockSubmissaoUseCaseMockRecorder struct {
	mock *MockSubmissaoUseCase
}

// NewMockSubmissaoUseCase creates a new mock instance.
func NewMockSubmissaoUseCase(ctrl *gomock.Controller) *MockSubmissaoUseCase {
	mock := &MockSubmissaoUseCase{ctrl: ctrl}
	mock.recorder = &MockSubmissaoUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubmissaoUseCase) EXPECT() *MockSubmissaoUseCaseMockRecorder {
	return m.recorder
}

// Submeter mocks base method.
func (m *MockSubmissaoUseCase) Submeter(ctx context.Context, sessionID string, raw json.RawMessage) (string, []validation.Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Submeter", ctx, sessionID, raw)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]validation.Issue)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Submeter indicates an expected call of Submeter.
func (mr *MockSubmissaoUseCaseMockRecorder) Submeter(ctx, sessionID, raw any) *MockSubmissaoUseCaseSubmeterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Submeter", reflect.TypeOf((*MockSubmissaoUseCase)(nil).Submeter), ctx, sessionID, raw)
	return &MockSubmissaoUseCaseSubmeterCall{Call: call}
}

// MockSubmissaoUseCaseSubmeterCall wrap *gomock.Call
type MockSubmissaoUseCaseSubmeterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSubmissaoUseCaseSubmeterCall) Return(arg0 string, arg1 []validation.Issue, arg2 error) *MockSubmissaoUseCaseSubmeterCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSubmissaoUseCaseSubmeterCall) Do(f func(context.Context, string, json.RawMessage) (string, []validation.Issue, error)) *MockSubmissaoUseCaseSubmeterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSubmissaoUseCaseSubmeterCall) DoAndReturn(f func(context.Context, string, json.RawMessage) (string, []validation.Issue, error)) *MockSubmissaoUseCaseSubmeterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
