import type { AberturaFormValues } from '@prolink/shared';
import { socioVazio } from './socioVazio';

export const devSeed: Partial<AberturaFormValues> = {
  dadosEmpresa: {
    tipoConstituicao: 'ltda',
    nomeEmpresarial1: 'Alfa Servicos Ltda',
    nomeEmpresarial2: 'Alfa Negocios Ltda',
    nomeEmpresarial3: 'Alfa Participacoes Ltda',
    nomeFantasia: 'Alfa',
    atividade: 'Prestacao de servicos contabeis e assessoria empresarial.',
  },
  endereco: {
    cep: '01310-100',
    logradouro: 'Avenida Paulista',
    numero: '1000',
    complemento: 'Sala 1',
    bairro: 'Bela Vista',
    municipio: 'Sao Paulo',
    estado: 'SP',
    iptu: '1-234-567-8',
    imovelAlugado: false,
  },
  dadosSocios: {
    socios: [
      {
        ...socioVazio(),
        nome: 'Joao da Silva',
        pis: '120.34567.89-0',
        cpf: '529.982.247-25',
        rg: '12.345.678-0 SSP/SP',
        nacionalidade: 'Brasileiro',
        profissao: 'Contador',
        proLabore: 3000,
        telefoneCelular: '(11) 99999-0001',
        telefoneFixo: '',
        email: 'joao@example.com',
        estadoCivil: 'solteiro',
        nomeMae: 'Maria da Silva',
        nomePai: 'Jose da Silva',
        cepRegistro: '01310-100',
        logradouroRegistro: 'Avenida Paulista',
        numeroRegistro: '1000',
        complementoRegistro: '',
        bairroRegistro: 'Bela Vista',
        registroConselho: '',
        teveParticipacaoSocietaria: false,
        cnpjParticipacao: '',
      },
      {
        ...socioVazio(),
        nome: 'Ana Souza',
        pis: '120.34567.89-1',
        cpf: '111.444.777-35',
        rg: '98.765.432-1 SSP/SP',
        nacionalidade: 'Brasileira',
        profissao: 'Administradora',
        proLabore: 3000,
        telefoneCelular: '(11) 99999-0002',
        telefoneFixo: '',
        email: 'ana@example.com',
        estadoCivil: 'casado_comunhao_parcial',
        nomeMae: 'Clara Souza',
        nomePai: 'Pedro Souza',
        cepRegistro: '01310-100',
        logradouroRegistro: 'Avenida Paulista',
        numeroRegistro: '1000',
        complementoRegistro: '',
        bairroRegistro: 'Bela Vista',
        registroConselho: '',
        teveParticipacaoSocietaria: false,
        cnpjParticipacao: '',
      },
    ],
  },
  sociedade: {
    capitalSocial: 50000,
    quotas: [
      { percentual: 50, isAdministrador: true },
      { percentual: 50, isAdministrador: false },
    ],
    tipoAdministracao: 'isoladamente',
    banco: 'Banco do Brasil',
  },
  senhaGovBr: '',
  documentosAceitos: false,
};
