// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tiagods/webtool/apps/backend/domain/ports/outbound (interfaces: AceiteRepository)
//
// Generated by this command:
//
//	mockgen -typed -package mocks -destination aceite_repository.go github.com/tiagods/webtool/apps/backend/domain/ports/outbound AceiteRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/tiagods/webtool/apps/backend/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockAceiteRepository is a mock of AceiteRepository interface.
type MockAceiteRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAceiteRepositoryMockRecorder
	isgomock struct{}
}

// MockAceiteRepositoryMockRecorder is the mock recorder for MockAceiteRepository.
type MockAceiteRepositoryMockRecorder struct {
	mock *MockAceiteRepository
}

// NewMockAceiteRepository creates a new mock instance.
func NewMockAceiteRepository(ctrl *gomock.Controller) *MockAceiteRepository {
	mock := &MockAceiteRepository{ctrl: ctrl}
	mock.recorder = &MockAceiteRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAceiteRepository) EXPECT() *MockAceiteRepositoryMockRecorder {
	return m.recorder
}

// Put mocks base method.
func (m *MockAceiteRepository) Put(ctx context.Context, registro entity.RegistroAceite) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, registro)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockAceiteRepositoryMockRecorder) Put(ctx, registro any) *MockAceiteRepositoryPutCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockAceiteRepository)(nil).Put), ctx, registro)
	return &MockAceiteRepositoryPutCall{Call: call}
}

// MockAceiteRepositoryPutCall wrap *gomock.Call
type MockAceiteRepositoryPutCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAceiteRepositoryPutCall) Return(arg0 error) *MockAceiteRepositoryPutCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAceiteRepositoryPutCall) Do(f func(context.Context, entity.RegistroAceite) error) *MockAceiteRepositoryPutCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAceiteRepositoryPutCall) DoAndReturn(f func(context.Context, entity.RegistroAceite) error) *MockAceiteRepositoryPutCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
