// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tiagods/webtool/apps/backend/domain/ports/outbound (interfaces: DocumentoStorage)
//
// Generated by this command:
//
//	mockgen -typed -package mocks -destination documento_storage.go github.com/tiagods/webtool/apps/backend/domain/ports/outbound DocumentoStorage
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockDocumentoStorage is a mock of DocumentoStorage interface.
type MockDocumentoStorage struct {
	ctrl     *gomock.Controller
	recorder *MockDocumentoStorageMockRecorder
	isgomock struct{}
}

// MockDocumentoStorageMockRecorder is the mock recorder for MockDocumentoStorage.
type MockDocumentoStorageMockRecorder struct {
	mock *MockDocumentoStorage
}

// NewMockDocumentoStorage creates a new mock instance.
func NewMockDocumentoStorage(ctrl *gomock.Controller) *MockDocumentoStorage {
	mock := &MockDocumentoStorage{ctrl: ctrl}
	mock.recorder = &MockDocumentoStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDocumentoStorage) EXPECT() *MockDocumentoStorageMockRecorder {
	return m.recorder
}

// Copy mocks base method.
func (m *MockDocumentoStorage) Copy(ctx context.Context, srcKey, destKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Copy", ctx, srcKey, destKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// Copy indicates an expected call of Copy.
func (mr *MockDocumentoStorageMockRecorder) Copy(ctx, srcKey, destKey any) *MockDocumentoStorageCopyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Copy", reflect.TypeOf((*MockDocumentoStorage)(nil).Copy), ctx, srcKey, destKey)
	return &MockDocumentoStorageCopyCall{Call: call}
}

// MockDocumentoStorageCopyCall wrap *gomock.Call
type MockDocumentoStorageCopyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDocumentoStorageCopyCall) Return(arg0 error) *MockDocumentoStorageCopyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDocumentoStorageCopyCall) Do(f func(context.Context, string, string) error) *MockDocumentoStorageCopyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDocumentoStorageCopyCall) DoAndReturn(f func(context.Context, string, string) error) *MockDocumentoStorageCopyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeletePrefix mocks base method.
func (m *MockDocumentoStorage) DeletePrefix(ctx context.Context, prefix string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePrefix", ctx, prefix)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePrefix indicates an expected call of DeletePrefix.
func (mr *MockDocumentoStorageMockRecorder) DeletePrefix(ctx, prefix any) *MockDocumentoStorageDeletePrefixCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePrefix", reflect.TypeOf((*MockDocumentoStorage)(nil).DeletePrefix), ctx, prefix)
	return &MockDocumentoStorageDeletePrefixCall{Call: call}
}

// MockDocumentoStorageDeletePrefixCall wrap *gomock.Call
type MockDocumentoStorageDeletePrefixCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDocumentoStorageDeletePrefixCall) Return(arg0 error) *MockDocumentoStorageDeletePrefixCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDocumentoStorageDeletePrefixCall) Do(f func(context.Context, string) error) *MockDocumentoStorageDeletePrefixCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDocumentoStorageDeletePrefixCall) DoAndReturn(f func(context.Context, string) error) *MockDocumentoStorageDeletePrefixCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PresignedDownloadURL mocks base method.
func (m *MockDocumentoStorage) PresignedDownloadURL(ctx context.Context, key string, expiresIn time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresignedDownloadURL", ctx, key, expiresIn)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignedDownloadURL indicates an expected call of PresignedDownloadURL.
func (mr *MockDocumentoStorageMockRecorder) PresignedDownloadURL(ctx, key, expiresIn any) *MockDocumentoStoragePresignedDownloadURLCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignedDownloadURL", reflect.TypeOf((*MockDocumentoStorage)(nil).PresignedDownloadURL), ctx, key, expiresIn)
	return &MockDocumentoStoragePresignedDownloadURLCall{Call: call}
}

// MockDocumentoStoragePresignedDownloadURLCall wrap *gomock.Call
type MockDocumentoStoragePresignedDownloadURLCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDocumentoStoragePresignedDownloadURLCall) Return(arg0 string, arg1 error) *MockDocumentoStoragePresignedDownloadURLCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDocumentoStoragePresignedDownloadURLCall) Do(f func(context.Context, string, time.Duration) (string, error)) *MockDocumentoStoragePresignedDownloadURLCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDocumentoStoragePresignedDownloadURLCall) DoAndReturn(f func(context.Context, string, time.Duration) (string, error)) *MockDocumentoStoragePresignedDownloadURLCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PresignedUploadURL mocks base method.
func (m *MockDocumentoStorage) PresignedUploadURL(ctx context.Context, key, contentType string, expiresIn time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresignedUploadURL", ctx, key, contentType, expiresIn)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignedUploadURL indicates an expected call of PresignedUploadURL.
func (mr *MockDocumentoStorageMockRecorder) PresignedUploadURL(ctx, key, contentType, expiresIn any) *MockDocumentoStoragePresignedUploadURLCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignedUploadURL", reflect.TypeOf((*MockDocumentoStorage)(nil).PresignedUploadURL), ctx, key, contentType, expiresIn)
	return &MockDocumentoStoragePresignedUploadURLCall{Call: call}
}

// MockDocumentoStoragePresignedUploadURLCall wrap *gomock.Call
type MockDocumentoStoragePresignedUploadURLCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDocumentoStoragePresignedUploadURLCall) Return(arg0 string, arg1 error) *MockDocumentoStoragePresignedUploadURLCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDocumentoStoragePresignedUploadURLCall) Do(f func(context.Context, string, string, time.Duration) (string, error)) *MockDocumentoStoragePresignedUploadURLCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDocumentoStoragePresignedUploadURLCall) DoAndReturn(f func(context.Context, string, string, time.Duration) (string, error)) *MockDocumentoStoragePresignedUploadURLCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PutJSON mocks base method.
func (m *MockDocumentoStorage) PutJSON(ctx context.Context, key string, data any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutJSON", ctx, key, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutJSON indicates an expected call of PutJSON.
func (mr *MockDocumentoStorageMockRecorder) PutJSON(ctx, key, data any) *MockDocumentoStoragePutJSONCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutJSON", reflect.TypeOf((*MockDocumentoStorage)(nil).PutJSON), ctx, key, data)
	return &MockDocumentoStoragePutJSONCall{Call: call}
}

// MockDocumentoStoragePutJSONCall wrap *gomock.Call
type MockDocumentoStoragePutJSONCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDocumentoStoragePutJSONCall) Return(arg0 error) *MockDocumentoStoragePutJSONCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDocumentoStoragePutJSONCall) Do(f func(context.Context, string, any) error) *MockDocumentoStoragePutJSONCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDocumentoStoragePutJSONCall) DoAndReturn(f func(context.Context, string, any) error) *MockDocumentoStoragePutJSONCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
