// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tiagods/webtool/apps/backend/domain/ports/outbound (interfaces: NotificacaoSender)
//
// Generated by this command:
//
//	mockgen -typed -package mocks -destination notificacao_sender.go github.com/tiagods/webtool/apps/backend/domain/ports/outbound NotificacaoSender
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	outbound "github.com/tiagods/webtool/apps/backend/domain/ports/outbound"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificacaoSender is a mock of NotificacaoSender interface.
type MockNotificacaoSender struct {
	ctrl     *gomock.Controller
	recorder *MockNotificacaoSenderMockRecorder
	isgomock struct{}
}

// MockNotificacaoSenderMockRecorder is the mock recorder for MockNotificacaoSender.
type MockNotificacaoSenderMockRecorder struct {
	mock *MockNotificacaoSender
}

// NewMockNotificacaoSender creates a new mock instance.
func NewMockNotificacaoSender(ctrl *gomock.Controller) *MockNotificacaoSender {
	mock := &MockNotificacaoSender{ctrl: ctrl}
	mock.recorder = &MockNotificacaoSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificacaoSender) EXPECT() *MockNotificacaoSenderMockRecorder {
	return m.recorder
}

// EnviarAbertura mocks base method.
func (m *MockNotificacaoSender) EnviarAbertura(ctx context.Context, n outbound.NotificacaoAbertura) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnviarAbertura", ctx, n)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnviarAbertura indicates an expected call of EnviarAbertura.
func (mr *MockNotificacaoSenderMockRecorder) EnviarAbertura(ctx, n any) *MockNotificacaoSenderEnviarAberturaCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnviarAbertura", reflect.TypeOf((*MockNotificacaoSender)(nil).EnviarAbertura), ctx, n)
	return &MockNotificacaoSenderEnviarAberturaCall{Call: call}
}

// MockNotificacaoSenderEnviarAberturaCall wrap *gomock.Call
type MockNotificacaoSenderEnviarAberturaCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockNotificacaoSenderEnviarAberturaCall) Return(arg0 error) *MockNotificacaoSenderEnviarAberturaCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockNotificacaoSenderEnviarAberturaCall) Do(f func(context.Context, outbound.NotificacaoAbertura) error) *MockNotificacaoSenderEnviarAberturaCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockNotificacaoSenderEnviarAberturaCall) DoAndReturn(f func(context.Context, outbound.NotificacaoAbertura) error) *MockNotificacaoSenderEnviarAberturaCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// EnviarAlteracao mocks base method.
func (m *MockNotificacaoSender) EnviarAlteracao(ctx context.Context, n outbound.NotificacaoAlteracao) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnviarAlteracao", ctx, n)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnviarAlteracao indicates an expected call of EnviarAlteracao.
func (mr *MockNotificacaoSenderMockRecorder) EnviarAlteracao(ctx, n any) *MockNotificacaoSenderEnviarAlteracaoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnviarAlteracao", reflect.TypeOf((*MockNotificacaoSender)(nil).EnviarAlteracao), ctx, n)
	return &MockNotificacaoSenderEnviarAlteracaoCall{Call: call}
}

// MockNotificacaoSenderEnviarAlteracaoCall wrap *gomock.Call
type MockNotificacaoSenderEnviarAlteracaoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockNotificacaoSenderEnviarAlteracaoCall) Return(arg0 error) *MockNotificacaoSenderEnviarAlteracaoCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockNotificacaoSenderEnviarAlteracaoCall) Do(f func(context.Context, outbound.NotificacaoAlteracao) error) *MockNotificacaoSenderEnviarAlteracaoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockNotificacaoSenderEnviarAlteracaoCall) DoAndReturn(f func(context.Context, outbound.NotificacaoAlteracao) error) *MockNotificacaoSenderEnviarAlteracaoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
