// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tiagods/webtool/apps/backend/domain/ports/outbound (interfaces: RascunhoRepository)
//
// Generated by this command:
//
//	mockgen -typed -package mocks -destination rascunho_repository.go github.com/tiagods/webtool/apps/backend/domain/ports/outbound RascunhoRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	json "encoding/json"
	reflect "reflect"

	entity "github.com/tiagods/webtool/apps/backend/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockRascunhoRepository is a mock of RascunhoRepository interface.
type MockRascunhoRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRascunhoRepositoryMockRecorder
	isgomock struct{}
}

// MockRascunhoRepositoryMockRecorder is the mock recorder for MockRascunhoRepository.
type MockRascunhoRepositoryMockRecorder struct {
	mock *MockRascunhoRepository
}

// NewMockRascunhoRepository creates a new mock instance.
func NewMockRascunhoRepository(ctrl *gomock.Controller) *MockRascunhoRepository {
	mock := &MockRascunhoRepository{ctrl: ctrl}
	mock.recorder = &MockRascunhoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRascunhoRepository) EXPECT() *MockRascunhoRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockRascunhoRepository) Delete(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRascunhoRepositoryMockRecorder) Delete(ctx, sessionID any) *MockRascunhoRepositoryDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRascunhoRepository)(nil).Delete), ctx, sessionID)
	return &MockRascunhoRepositoryDeleteCall{Call: call}
}

// MockRascunhoRepositoryDeleteCall wrap *gomock.Call
type MockRascunhoRepositoryDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRascunhoRepositoryDeleteCall) Return(arg0 error) *MockRascunhoRepositoryDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRascunhoRepositoryDeleteCall) Do(f func(context.Context, string) error) *MockRascunhoRepositoryDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRascunhoRepositoryDeleteCall) DoAndReturn(f func(context.Context, string) error) *MockRascunhoRepositoryDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// EnsureInicial mocks base method.
func (m *MockRascunhoRepository) EnsureInicial(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureInicial", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureInicial indicates an expected call of EnsureInicial.
func (mr *MockRascunhoRepositoryMockRecorder) EnsureInicial(ctx, sessionID any) *MockRascunhoRepositoryEnsureInicialCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureInicial", reflect.TypeOf((*MockRascunhoRepository)(nil).EnsureInicial), ctx, sessionID)
	return &MockRascunhoRepositoryEnsureInicialCall{Call: call}
}

// MockRascunhoRepositoryEnsureInicialCall wrap *gomock.Call
type MockRascunhoRepositoryEnsureInicialCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRascunhoRepositoryEnsureInicialCall) Return(arg0 error) *MockRascunhoRepositoryEnsureInicialCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRascunhoRepositoryEnsureInicialCall) Do(f func(context.Context, string) error) *MockRascunhoRepositoryEnsureInicialCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRascunhoRepositoryEnsureInicialCall) DoAndReturn(f func(context.Context, string) error) *MockRascunhoRepositoryEnsureInicialCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockRascunhoRepository) Get(ctx context.Context, sessionID string) (*entity.Rascunho, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, sessionID)
	ret0, _ := ret[0].(*entity.Rascunho)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRascunhoRepositoryMockRecorder) Get(ctx, sessionID any) *MockRascunhoRepositoryGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRascunhoRepository)(nil).Get), ctx, sessionID)
	return &MockRascunhoRepositoryGetCall{Call: call}
}

// MockRascunhoRepositoryGetCall wrap *gomock.Call
type MockRascunhoRepositoryGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRascunhoRepositoryGetCall) Return(arg0 *entity.Rascunho, arg1 error) *MockRascunhoRepositoryGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRascunhoRepositoryGetCall) Do(f func(context.Context, string) (*entity.Rascunho, error)) *MockRascunhoRepositoryGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRascunhoRepositoryGetCall) DoAndReturn(f func(context.Context, string) (*entity.Rascunho, error)) *MockRascunhoRepositoryGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MarcarEnviado mocks base method.
func (m *MockRascunhoRepository) MarcarEnviado(ctx context.Context, sessionID, protocolo string, tipo entity.TipoConstituicao) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarcarEnviado", ctx, sessionID, protocolo, tipo)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarcarEnviado indicates an expected call of MarcarEnviado.
func (mr *MockRascunhoRepositoryMockRecorder) MarcarEnviado(ctx, sessionID, protocolo, tipo any) *MockRascunhoRepositoryMarcarEnviadoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarcarEnviado", reflect.TypeOf((*MockRascunhoRepository)(nil).MarcarEnviado), ctx, sessionID, protocolo, tipo)
	return &MockRascunhoRepositoryMarcarEnviadoCall{Call: call}
}

// MockRascunhoRepositoryMarcarEnviadoCall wrap *gomock.Call
type MockRascunhoRepositoryMarcarEnviadoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRascunhoRepositoryMarcarEnviadoCall) Return(arg0 error) *MockRascunhoRepositoryMarcarEnviadoCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRascunhoRepositoryMarcarEnviadoCall) Do(f func(context.Context, string, string, entity.TipoConstituicao) error) *MockRascunhoRepositoryMarcarEnviadoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRascunhoRepositoryMarcarEnviadoCall) DoAndReturn(f func(context.Context, string, string, entity.TipoConstituicao) error) *MockRascunhoRepositoryMarcarEnviadoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PutDocumentoKey mocks base method.
func (m *MockRascunhoRepository) PutDocumentoKey(ctx context.Context, sessionID, campo, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutDocumentoKey", ctx, sessionID, campo, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutDocumentoKey indicates an expected call of PutDocumentoKey.
func (mr *MockRascunhoRepositoryMockRecorder) PutDocumentoKey(ctx, sessionID, campo, key any) *MockRascunhoRepositoryPutDocumentoKeyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutDocumentoKey", reflect.TypeOf((*MockRascunhoRepository)(nil).PutDocumentoKey), ctx, sessionID, campo, key)
	return &MockRascunhoRepositoryPutDocumentoKeyCall{Call: call}
}

// MockRascunhoRepositoryPutDocumentoKeyCall wrap *gomock.Call
type MockRascunhoRepositoryPutDocumentoKeyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRascunhoRepositoryPutDocumentoKeyCall) Return(arg0 error) *MockRascunhoRepositoryPutDocumentoKeyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRascunhoRepositoryPutDocumentoKeyCall) Do(f func(context.Context, string, string, string) error) *MockRascunhoRepositoryPutDocumentoKeyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRascunhoRepositoryPutDocumentoKeyCall) DoAndReturn(f func(context.Context, string, string, string) error) *MockRascunhoRepositoryPutDocumentoKeyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PutPayload mocks base method.
func (m *MockRascunhoRepository) PutPayload(ctx context.Context, sessionID string, payload json.RawMessage, tipo entity.TipoConstituicao) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutPayload", ctx, sessionID, payload, tipo)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutPayload indicates an expected call of PutPayload.
func (mr *MockRascunhoRepositoryMockRecorder) PutPayload(ctx, sessionID, payload, tipo any) *MockRascunhoRepositoryPutPayloadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutPayload", reflect.TypeOf((*MockRascunhoRepository)(nil).PutPayload), ctx, sessionID, payload, tipo)
	return &MockRascunhoRepositoryPutPayloadCall{Call: call}
}

// MockRascunhoRepositoryPutPayloadCall wrap *gomock.Call
type MockRascunhoRepositoryPutPayloadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRascunhoRepositoryPutPayloadCall) Return(arg0 error) *MockRascunhoRepositoryPutPayloadCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRascunhoRepositoryPutPayloadCall) Do(f func(context.Context, string, json.RawMessage, entity.TipoConstituicao) error) *MockRascunhoRepositoryPutPayloadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRascunhoRepositoryPutPayloadCall) DoAndReturn(f func(context.Context, string, json.RawMessage, entity.TipoConstituicao) error) *MockRascunhoRepositoryPutPayloadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
